// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClientOptions } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing Supabase environment variables!');
  throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Opções para o cliente Supabase - CONFIGURAÇÃO OTIMIZADA PARA EVITAR LOGOUT AUTOMÁTICO
const supabaseOptions: SupabaseClientOptions<"public"> = {
  auth: {
    storage: localStorage, // Usar localStorage para permitir atualizações de página
    autoRefreshToken: true, // Manter refresh automático
    persistSession: true, // Manter persistência para evitar logout
    detectSessionInUrl: false, // DESABILITAR para evitar conflitos com mudanças de URL
    flowType: 'pkce' // Usar PKCE flow para melhor segurança
  },
  // Configurações globais para evitar timeouts
  global: {
    headers: {
      'X-Client-Info': 'panifpro-web-client'
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);